Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -42,6 +42,5 @@ jobs:
 
     - name: Run Tests
       run: |
-        cd build
-        echo $(pwd)
-        ./SKT_Lab02 || { echo "Test run failed"; exit 1; }
+        cd skt_lab02
+        ../build/SKT_Lab02 || { echo "Test run failed"; exit 1; }
