Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -32,7 +32,7 @@ jobs:
       run: |
         mkdir -p build
         cd build
-        cmake ${{ github.workspace }}/skt_lab02 -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release || { echo "CMake configuration failed"; exit 1; }
+        cmake ../skt_lab02 -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release || { echo "CMake configuration failed"; exit 1; }
         ls -la # Проверка содержимого папки сборки
 
     - name: Build Project
@@ -42,5 +42,5 @@ jobs:
 
     - name: Run Tests
       run: |
-        cd skt_lab02
-        ../build/SKT_Lab02 || { echo "Test run failed"; exit 1; }
+        cd build
+        ./SKT_Lab02 || { echo "Test run failed"; exit 1; }
