Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -22,6 +22,8 @@ jobs:
         ls -la
         echo "Contents of workspace:"
         ls -la ${{ github.workspace }}
+        echo "Contents of skt_lab02:"
+        ls -la ${{ github.workspace }}/skt_lab02
 
     - name: Install dependencies
       run: sudo apt-get update && sudo apt-get install -y cmake build-essential
@@ -30,8 +32,8 @@ jobs:
       run: |
         mkdir -p build
         cd build
-        cmake ${{ github.workspace }} -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release || { echo "CMake configuration failed"; exit 1; }
-        ls -la
+        cmake ${{ github.workspace }}/skt_lab02 -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release || { echo "CMake configuration failed"; exit 1; }
+        ls -la # Проверка содержимого папки сборки
 
     - name: Build Project
       run: |
