Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -20,7 +20,7 @@ jobs:
       run: |
         echo "Current directory: $(pwd)"
         ls -la
-        echo "Contents of project folder:"
+        echo "Contents of workspace:"
         ls -la ${{ github.workspace }}
 
     - name: Install dependencies
@@ -30,7 +30,7 @@ jobs:
       run: |
         mkdir -p build
         cd build
-        cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release || { echo "CMake configuration failed"; exit 1; }
+        cmake ${{ github.workspace }} -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release || { echo "CMake configuration failed"; exit 1; }
         ls -la
 
     - name: Build Project
